name: Deploy to Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
        coverage: none
        
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - name: Create cache directory
      run: mkdir -p var/cache/twig
      
    - name: Set permissions
      run: |
        chmod -R 755 var/
        chmod -R 755 public/
        
    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.FTP_TARGET_DIR }}
        exclude: |
          **/.git
          **/.github
          **/vendor
          **/node_modules
          **/.env